[environment]


[execution]
aggr_ses_reports = 4
boilerplate_only = false
debug = []
log_level = 25
low_mem = false
md_only_boilerplate = false
notrack = false
output_layout = "auto"
report_output_level = "root"
reports_only = false
write_graph = false

[workflow]
mode = "linc"
file_format = "auto" # Possible choices: auto, nifti, cifti
dummy_scans = "auto"
input_type = "fmriprep"
despike = true
smoothing = 4.0
output_interpolated = true
combine_runs = true
correlation_lengths = []
process_surfaces = true
abcc_qc = true
linc_qc = true
# watch out for the option --motion-filter-type, which can be set to:
# Possible choices: lp, notch, none
motion_filter_type = "lp"
band_stop_min = 6.0
# Type of filter to use for removing respiratory artifact from motion regressors. If not set, no filter will be applied.

[nipype]
crashfile_format = "txt"
get_linked_libs = false
plugin = "MultiProc"
resource_monitor = false
stop_on_first_crash = true