[environment]

[execution]
bids_dir = ""
boilerplate_only = false
sloppy = false
debug = []
log_level = 25
low_mem = false
md_only_boilerplate = false
notrack = false
track_carbon = false
me_output_echos = false
aggr_ses_reports = 4
output_layout = "bids"
reports_only = false
write_graph = false

[workflow]
anat_only = false
bold2anat_dof = 6
bold2anat_init = "auto"
fmap_bspline = false
force_syn = false
hires = true
fs_no_resume = false
ignore = [ "slicetiming",]
force = []
level = "full"
run_msmsulc = true
medial_surface_nan = false
project_goodvoxels = true
regressors_all_comps = false
regressors_dvars_th = 2.0
regressors_fd_th = 0.5
run_reconall = true
skull_strip_fixed_seed = false
skull_strip_template = "OASIS30ANTs"
skull_strip_t1w = "force"
slice_time_ref = 0.5
use_syn_sdc = false
me_t2s_fit_method = "curvefit"

[nipype]
crashfile_format = "txt"
get_linked_libs = false
plugin = "MultiProc"
remove_unnecessary_outputs = false
resource_monitor = false
stop_on_first_crash = false