#bids_filter_file = ""
#bids_database_dir = ""
#nprocs = None
#omp_nthreads = None
#mem = None
#low_mem = None
nipype_plugin_file = ""
sloppy = false
anat_only = false
dwi_only = false
boilerplate_only = false
reports_only = false
ignore = []
infant = false
#longitudinal = None
subject_anatomical_reference = "first_alphabetically"
skip_anat_based_spatial_normalization = false
anat_modality = "T1w"
b0_threshold = 50
dwi_denoise_window = "auto"
denoise_method = "dwidenoise"
unringing_method = "mrdegibbs"
b1_biascorrect_stage = "final"
no_b0_harmonization = false
denoise_after_combining = false
separate_all_dwis = false
distortion_group_merge = "average"
anatomical_template = "MNI152NLin2009cAsym"
b0_to_t1w_transform = "Rigid"
intramodal_template_iters = 0
intramodal_template_transform = "BSplineSyN"
b0_motion_corr_to = "iterative"
hmc_transform = "Affine"
hmc_model = "eddy"
shoreline_iters = 2
pepolar_method = "TOPUP"
fmap_bspline = false
fmap_no_demean = true
use_syn_sdc = false
force_syn = false
verbose = true
resource_monitor = false
write_graph = false
stop_on_first_crash = false
notrack = false
#debug = None